apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu
  namespace: default
  annotations:
    cluster-group-upgrades-operator/name-suffix: kuttl      
spec:
  managedPolicies:
    - policy0-common-config-policy
    - policy1-common-cluster-version-policy
  enable: false
  clusters:
  - spoke1
  remediationStrategy:
    maxConcurrency: 4
