---
version: "2"

linters:
  enable:
    - depguard
    - goconst
    - gocritic
    - revive
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unparam
    - gocyclo
    - unused
  settings:
    depguard:
      rules:
        main:
          deny:
            - desc: Should be replaced by standard lib errors package
              pkg: "github.com/pkg/errors"
          files:
            - $all
          list-mode: lax
    gocritic:
      enabled-checks:
        # Diagnostic (keeping only non-default ones)
        - commentedOutCode
        - nilValReturn
        - weakCond
        - octalLiteral
        - sloppyReassign
        # Performance
        - equalFold
        - indexAlloc
        - rangeExprCopy
        - appendCombine
        # Style (keeping only non-default ones)
        - boolExprSimplify
        - commentedOutImport
        - docStub
        - emptyFallthrough
        - emptyStringTest
        - hexLiteral
        - methodExprCall
        - stringXbytes
        - typeAssertChain
        - unlabelStmt
        - yodaStyleExpr
        # Opinionated
        - initClause
        - nestingReduce
        - ptrToRefParam
        - typeUnparen
        - unnecessaryBlock
        - paramTypeCombine
    revive:
      rules:
        - disabled: true
          name: if-return
          severity: warning

formatters:
  enable:
    - gofmt
    - goimports

run:
  concurrency: 6
  timeout: 5m
