FROM registry.ci.openshift.org/ocp/4.10:base
RUN mkdir /opt/precache
COPY pre-cache/release \
     pre-cache/common \
     pre-cache/olm \
     pre-cache/parse_index.py \
     pre-cache/pull \
     pre-cache/precache.sh \
     pre-cache/copy-env.sh \
     /opt/precache
COPY pre-cache/storage.conf /etc/containers/
ENV PATH="/opt/precache:/host/usr/bin:/host/usr/libexec:${PATH}"
ENV LD_LIBRARY_PATH="/host/usr/lib64"
