ARG BASE_UBI_IMAGE
FROM ${BASE_UBI_IMAGE}

RUN mkdir /opt/precache

COPY pre-cache/release.sh \
     pre-cache/common.sh \
     pre-cache/olm.sh \
     pre-cache/parse_index.py \
     pre-cache/pull.sh \
     pre-cache/precache.sh \
     pre-cache/check_space.sh \
     /opt/precache/
