apiVersion: ran.openshift.io/v1alpha1
kind: Group
metadata:
  name: group1
  namespace: default
spec:
  sites:
    - site1
    - site2
  remediationStrategy:
    maxConcurrency: 1
  remediationAction: inform
