apiVersion: kuttl.dev/v1beta1
kind: TestSuite

commands:
  - command: oc apply -f deploy/acm/managed-clusters/setup-managed-spoke-clusters-namespaces.yaml
    namespaced: true
  - command: oc apply -f deploy/acm/managed-clusters/setup-managed-spoke-clusters.yaml
    namespaced: true

testDirs:
- tests/kuttl/cgu/
- tests/kuttl/ibgu/
crdDir: ./config/crd/bases/
timeout: 25
parallel: 1
namespace: default

#startControlPlane: true
#startKIND: true
#kindNodeCache: true
