apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
- tests/kuttl/tests/
crdDir: ./config/crd/bases/
timeout: 60
parallel: 1

namespace: default

#startControlPlane: true
#startKIND: true
#kindNodeCache: true
