apiVersion: kuttl.dev/v1beta1
kind: TestSuite

commands:
  - command: oc apply -f deploy/acm/managed-clusters/setup-managed-spoke-clusters-namespaces.yaml
    namespaced: true
  - command: oc apply -f deploy/acm/managed-clusters/setup-managed-spoke-clusters.yaml
    namespaced: true

testDirs:
- tests/kuttl/tests/
crdDir: ./config/crd/bases/
# The operator has a reconcile loop of 5 minutes, so we need to wait at least that amount of time
# before deciding to error.
timeout: 375
parallel: 1
namespace: default

#startControlPlane: true
#startKIND: true
#kindNodeCache: true
