apiVersion: ran.openshift.io/v1alpha1
kind: Site
metadata:
  name: site2
  namespace: default
spec:
  cluster: spoke2
  sitePolicyTemplates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: Policy
        metadata:
          name: site2-namespace
          annotations:
            policy.open-cluster-management.io/standards: NIST 800-53
            policy.open-cluster-management.io/categories: CM Configuration Management
            policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
        spec:
          remediationAction: inform
          disabled: false
          policy-templates:
            - objectDefinition:
                apiVersion: policy.open-cluster-management.io/v1
                kind: ConfigurationPolicy
                metadata:
                  name: policy-namespace-site2-ns
                spec:
                  remediationAction: inform # will be overridden by remediationAction in parent policy
                  severity: low
                  namespaceSelector:
                    exclude: ["kube-*"]
                    include: ["default"]
                  object-templates:
                    - complianceType: musthave
                      objectDefinition:
                        kind: Namespace # must have namespace 'site2'
                        apiVersion: v1
                        metadata:
                          name: site2
