#!/bin/bash

cwd="${cwd:-/opt/precache}"
. $cwd/common

extract_pull_spec(){
    rendered_index=$1
    operators_spec_file=$2
    pull_spec_file=$3
    /host/usr/libexec/platform-python /opt/precache/parse_index.py "${rendered_index}" "${operators_spec_file}" "${pull_spec_file}"
    return $?
}

render_index(){
    index=$1
    packages=$2
    image_mount=$3
    
    capath="/host/etc/docker/certs.d/${index%/*}/ca.crt"
    # opm doesn't accept cacert as an arg
    if [[ -f "$capath" ]]; then
        cp $capath /etc/pki/ca-trust/source/anchors/ 
        update-ca-trust
    fi
    if [[ -h "$image_mount/bin/opm" ]]; then
        opm_bin=$image_mount$(readlink "$image_mount/bin/opm")
    else
        opm_bin=$image_mount/bin/opm
    fi

    $opm_bin render $index > $rendered_index_path
    if [[ $? -ne 0 ]]; then
        return 1
    fi

}

extract_packages(){
    local packages
    cat $config_volume_path/operators.packagesAndChannels |tr -d " " > /tmp/packagesAndChannels
    for item in $(sort -u '/tmp/packagesAndChannels'); do
        pkg=$(echo $item |cut -d ':' -f 1)
        packages="$packages$pkg,"
    done
    echo ${packages%,}
    return 0
}

olm_main(){
    if ! [[ -n $(sort -u $config_volume_path/operators.indexes) ]]; then
      log_debug "Operators index is not specified. Operators won't be pre-cached"
      return 0
    fi
    # There could be several indexes, hence the loop
    for index in $(sort -u $config_volume_path/operators.indexes) ; do

        image_id=$(pull_index $index $pull_secret_path)
        if [[ $? -ne 0 ]]; then
          log_debug "pull_index failed for index $index"
          return 1
        fi
        log_debug "$index image ID is $image_id"
        image_mount=$(mount_index $image_id)
        if [[ $? -ne 0 ]]; then
          log_debug "mount_index failed for index $index"
          return 1
        fi
        log_debug "Image mount: $image_mount"
        packages=$(extract_packages)
        if ! [[ -n $packages ]]; then
          log_debug "operators index is set, but no packages provided - inconsistent configuration"
          return 1
        fi
        render_index $index $packages $image_mount
        if [[ $? -ne 0 ]]; then
          log_debug "render_index failed: OLM index render failed for index $index, package(s) $packages"
          return 1
        fi
        operators_spec_file="$config_volume_path/operators.packagesAndChannels"
        extract_pull_spec $rendered_index_path $operators_spec_file $pull_spec_file
        if [[ $? -ne 0 ]]; then
          log_debug "extract_pull_spec failed"
          return 1
        fi
        unmount_index $image_id
    done
    return 0
}

if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
  olm_main
  exit $?
fi
