#!/bin/bash

cwd=$(dirname "$0")
. $cwd/common

extract_pull_spec(){
    local rel_img_mount=$1

    # remove empty lines
    sed -i '/^[[:space:]]*$/d' $config_volume_path/excludePrecachePatterns
    # remove trailing and leading whitespace
    sed -i 's/^[ \t]*//;s/[ \t]*$//' $config_volume_path/excludePrecachePatterns
    
    cat ${rel_img_mount}/release-manifests/image-references | \
      jq  '.spec.tags[] | .name as $name |.from.name as $pull |[$name,$pull] |join("$")' | \
       grep -vG -f $config_volume_path/excludePrecachePatterns | \
       cut -d "$" -f2 | \
       sed 's/^/"/' >> $pull_spec_file
    log_debug "Release index image processing done"
}

release_main(){
    rel_img=$(cat $config_volume_path/platform.image)
    if ! [[ -n $rel_img ]]; then
      log_debug "Release index is not specified. Release images will not be pre-cached"
      return 0
    fi
    release_index_id=$(pull_index $rel_img $pull_secret_path)
    [[ $? -eq 0 ]] || return 1
    rel_img_mount=$(mount_index $release_index_id)
    [[ $? -eq 0 ]] || return 1
    extract_pull_spec $rel_img_mount
    [[ $? -eq 0 ]] || return 1
    unmount_index $release_index_id
    [[ $? -eq 0 ]] || return 1
    return 0
}

if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
  release_main
  exit $?
fi
