apiVersion: lcm.openshift.io/v1alpha1
kind: ImageBasedGroupUpgrade
metadata:
  name: upgrade-4.15.0
  namespace: default
  annotations:
    cluster-group-upgrades-operator/name-suffix: kuttl
    auto-rollback-on-failure.lca.openshift.io/post-reboot-config: Disabled
    auto-rollback-on-failure.lca.openshift.io/upgrade-completion: Disabled
    auto-rollback-on-failure.lca.openshift.io/init-monitor: Disabled
spec:
  clusterLabelSelectors:
    - matchExpressions:
        - key: "name"
          operator: In
          values:
            - "spoke1"
            - "spoke4"
            - "spoke6"        
  ibuSpec:
    seedImageRef:
      image: quay.io/seed/image:4.15.0-rc.5
      version: 4.15.0-rc.5
  plan:
    - actions: ["Prep"]
      rolloutStrategy:
        maxConcurrency: 2
        timeout: 2400
