apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: example-placementbinding
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-policy-trustednode
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: example-policy
