apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
    annotations:
        policy.open-cluster-management.io/categories: CM Configuration Management
        policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
        policy.open-cluster-management.io/standards: NIST SP 800-53
        ran.openshift.io/ztp-deploy-wave: "2"
    name: policy5-subscriptions
    namespace: default
spec:
    remediationAction: inform
    disabled: false
    policy-templates:
        - objectDefinition:
            apiVersion: policy.open-cluster-management.io/v1
            kind: ConfigurationPolicy
            metadata:
                name: common-subscriptions-policy-config
            spec:
                remediationAction: enforce
                severity: low
                namespaceselector:
                    exclude:
                        - kube-*
                    include:
                        - '*'
                object-templates:
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: operators.coreos.com/v1alpha1
                        kind: Subscription
                        metadata:
                            annotations:
                                ran.openshift.io/ztp-deploy-wave: "2"
                            name: sriov-network-operator-subscription
                            namespace: openshift-sriov-network-operator
                        spec:
                            channel: "4.9"
                            name: sriov-network-operator
                            source: redhat-operators
                            sourceNamespace: openshift-marketplace
                            installPlanApproval: Manual
                        status:
                            state: AtLatestKnown
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: v1
                        kind: Namespace
                        metadata:
                            annotations:
                                ran.openshift.io/ztp-deploy-wave: "2"
                                workload.openshift.io/allowed: management
                            labels:
                                openshift.io/run-level: "1"
                            name: openshift-sriov-network-operator
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: operators.coreos.com/v1
                        kind: OperatorGroup
                        metadata:
                            annotations:
                                ran.openshift.io/ztp-deploy-wave: "2"
                            name: sriov-network-operators
                            namespace: openshift-sriov-network-operator
                        spec:
                            targetNamespaces:
                                - openshift-sriov-network-operator
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: operators.coreos.com/v1alpha1
                        kind: Subscription
                        metadata:
                            annotations:
                                ran.openshift.io/ztp-deploy-wave: "2"
                            name: ptp-operator-subscription
                            namespace: openshift-ptp
                        spec:
                            channel: "4.9"
                            name: ptp-operator
                            source: redhat-operators
                            sourceNamespace: openshift-marketplace
                            installPlanApproval: Manual
                        status:
                            state: AtLatestKnown
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: v1
                        kind: Namespace
                        metadata:
                            annotations:
                                ran.openshift.io/ztp-deploy-wave: "2"
                                workload.openshift.io/allowed: management
                            labels:
                                openshift.io/cluster-monitoring: "true"
                            name: openshift-ptp
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: operators.coreos.com/v1
                        kind: OperatorGroup
                        metadata:
                            annotations:
                                ran.openshift.io/ztp-deploy-wave: "2"
                            name: ptp-operators
                            namespace: openshift-ptp
                        spec:
                            targetNamespaces:
                                - openshift-ptp
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: operators.coreos.com/v1alpha1
                        kind: Subscription
                        metadata:
                            annotations:
                                ran.openshift.io/ztp-deploy-wave: "2"
                            name: performance-addon-operator
                            namespace: openshift-performance-addon-operator
                        spec:
                            channel: "4.9"
                            name: performance-addon-operator
                            source: redhat-operators
                            sourceNamespace: openshift-marketplace
                            installPlanApproval: Manual
                        status:
                            state: AtLatestKnown
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: v1
                        kind: Namespace
                        metadata:
                            annotations:
                                ran.openshift.io/ztp-deploy-wave: "2"
                                workload.openshift.io/allowed: management
                            labels:
                                openshift.io/cluster-monitoring: "true"
                            name: openshift-performance-addon-operator
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: operators.coreos.com/v1
                        kind: OperatorGroup
                        metadata:
                            annotations:
                                ran.openshift.io/ztp-deploy-wave: "2"
                            name: performance-addon-operator
                            namespace: openshift-performance-addon-operator
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: v1
                        kind: Namespace
                        metadata:
                            annotations:
                                ran.openshift.io/ztp-deploy-wave: "2"
                                workload.openshift.io/allowed: management
                            name: openshift-logging
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: operators.coreos.com/v1
                        kind: OperatorGroup
                        metadata:
                            annotations:
                                ran.openshift.io/ztp-deploy-wave: "2"
                            name: cluster-logging
                            namespace: openshift-logging
                        spec:
                            targetNamespaces:
                                - openshift-logging
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: operators.coreos.com/v1alpha1
                        kind: Subscription
                        metadata:
                            annotations:
                                ran.openshift.io/ztp-deploy-wave: "2"
                            name: cluster-logging
                            namespace: openshift-logging
                        spec:
                            channel: stable
                            name: cluster-logging
                            source: redhat-operators
                            sourceNamespace: openshift-marketplace
                            installPlanApproval: Manual
                        status:
                            state: AtLatestKnown
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: v1
                        kind: Namespace
                        metadata:
                            annotations:
                                ran.openshift.io/ztp-deploy-wave: "2"
                                workload.openshift.io/allowed: management
                            name: openshift-local-storage
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: operators.coreos.com/v1
                        kind: OperatorGroup
                        metadata:
                            annotations:
                                ran.openshift.io/ztp-deploy-wave: "2"
                            name: openshift-local-storage
                            namespace: openshift-local-storage
                        spec:
                            targetNamespaces:
                                - openshift-local-storage
                    - complianceType: musthave
                      objectDefinition:
                        apiVersion: operators.coreos.com/v1alpha1
                        kind: Subscription
                        metadata:
                            annotations:
                                ran.openshift.io/ztp-deploy-wave: "2"
                            name: local-storage-operator
                            namespace: openshift-local-storage
                        spec:
                            channel: "4.9"
                            installPlanApproval: Manual
                            name: local-storage-operator
                            source: redhat-operators
                            sourceNamespace: openshift-marketplace
                        status:
                            state: AtLatestKnown
