apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-soaking
  namespace: default
  annotations:
    cluster-group-upgrades-operator/name-suffix: kuttl      
spec:
  actions:
    afterCompletion:
      addClusterLabels:
        ztp-done: ''
      deleteClusterLabels:
        ztp-running: ''
      deleteObjects: true
    beforeEnable:
      addClusterLabels:
        ztp-running: ''
  managedPolicies:
    - policy1-common-cluster-version-policy
  enable: true
  clusters:
  - spoke1
  remediationStrategy:
    maxConcurrency: 1
