# permissions for end users to view ClusterGroupUpgrades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ClusterGroupUpgrade-viewer-role
rules:
- apiGroups:
  - ran.openshift.io
  resources:
  - ClusterGroupUpgrades
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ran.openshift.io
  resources:
  - ClusterGroupUpgrades/status
  verbs:
  - get
