# permissions for end users to edit ClusterGroupUpgrades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ClusterGroupUpgrade-editor-role
rules:
- apiGroups:
  - ran.openshift.io
  resources:
  - ClusterGroupUpgrades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ran.openshift.io
  resources:
  - ClusterGroupUpgrades/status
  verbs:
  - get
