# permissions for end users to edit PreCachingConfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: PreCachingConfig-editor-role
rules:
- apiGroups:
  - ran.openshift.io
  resources:
  - PreCachingConfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ran.openshift.io
  resources:
  - PreCachingConfigs/status
  verbs:
  - get
