# permissions for end users to view PreCachingConfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: PreCachingConfig-viewer-role
rules:
- apiGroups:
  - ran.openshift.io
  resources:
  - PreCachingConfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ran.openshift.io
  resources:
  - PreCachingConfig/status
  verbs:
  - get
