# We can consume this arg to check whether a build is in Konflux or not
KONFLUX=true
#

# The builder image is used to compile golang code
BUILDER_IMAGE=brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.22@sha256:bad07005540854895705a954d8ffcee834862f57c129514ee02284eff3d251bb
#

# The opm image is used to serve the FBC
# There is a metadata processing bug preventing us from pinning this particular image for now
# OPM_IMAGE=registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.16@sha256:52d96341d4ceea3b5a5583f3b0bc057c01a6110f7a9ea0290d49218229b9f5ed
#

# The runtime image is used to run the binaries
RUNTIME_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:c5478a52c410e71c53839923c83a1480199a1e74ce5736fe3e3a5578dc399102
#

# The yq image is used at build time to manipulate yaml
YQ_IMAGE=quay.io/konflux-ci/yq:latest@sha256:e2b71e05fdb2a81fff75da6668c99d95da4a6c64224cc1262c9ee42348171fab
#
