# We can consume this arg to check whether a build is in Konflux or not
KONFLUX=true
#

# The builder image is used to compile golang code
BUILDER_IMAGE=brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.19@sha256:08316d1d9032a0440a1ba68b8dccaa8fdf65c4f3baa99e3718f5096774b4d7ea
#

# The opm image is used to serve the FBC
# There is a metadata processing bug preventing us from pinning this particular image for now
# OPM_IMAGE=registry.redhat.io/openshift4/ose-operator-registry:v4.14@sha256:a178ce43495751a25ac01a620edf4a48c2a5f8d5a6a5707b8091a88e1b35191d
#

# The runtime image is used to run the binaries
RUNTIME_IMAGE=registry.access.redhat.com/ubi8-minimal:latest@sha256:7eedea3d199fd9b0e6a06cd1a22537c1b84fab65d6eec8a5049c12e68c57f692
#

# The yq image is used at build time to manipulate yaml
YQ_IMAGE=quay.io/konflux-ci/yq:latest@sha256:9b73d39c362692d0bc5787c2b5e955cd54713e6bb97195a0fb2e87a6557040ee
#