# We can consume this arg to check whether a build is in Konflux or not
KONFLUX=true
#

# The builder image is used to compile golang code
BUILDER_IMAGE=brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.22@sha256:79c43dceb4fa898c8fb2aa311fd17742da6251a45a35d4dce093a898e6d0781e
#

# The opm image is used to serve the FBC
# There is a metadata processing bug preventing us from pinning this particular image for now
# OPM_IMAGE=registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.16@sha256:769e8b7078e76bd603f9ee52a8c14feef627187a898677fc97e7ee63e95c8867
#

# The runtime image is used to run the binaries
RUNTIME_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:7b8e25a1b56ca4d00219198f3b5b51a3e1693a5c4f5369c5e190d7d6cb3f980e
#

# The yq image is used at build time to manipulate yaml
YQ_IMAGE=quay.io/konflux-ci/yq:latest@sha256:9b73d39c362692d0bc5787c2b5e955cd54713e6bb97195a0fb2e87a6557040ee
#
