# The opm image is expected to contain /bin/opm (with a serve subcommand) and /bin/grpc_health_probe
ARG OPM_IMAGE=registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.18
ARG BUILDER_IMAGE=registry.redhat.io/openshift/golang-builder:golang-builder-v1.23-rhel9@sha256:50d66d211c063b0b9c32c57e7a6a41937355428bceac3efa64391a2ee581f33f

# fix the catalog (talm exclusive, naming issue)
FROM ${BUILDER_IMAGE} AS builder

# create dir structure to fix the catalog
RUN mkdir -p /app/.konflux/catalog
COPY Makefile /app
COPY .konflux/catalog/ /app/.konflux/catalog/
# we need to copy the vendor/ folder as the Makefile depends on it
COPY vendor/ /app/vendor/

WORKDIR /app
RUN SKIP_SUBMODULE_SYNC=yes make konflux-fix-catalog-name

# run the catalog
FROM ${OPM_IMAGE}

ENTRYPOINT ["/bin/opm"]
CMD ["serve", "/configs", "--cache-dir=/tmp/cache"]

# ensure this correponds to olm.package name
ENV PACKAGE_NAME=topology-aware-lifecycle-manager

# This assumes that the catalog is already built and exists in the .konflux/catalog/$PACKAGE_NAME directory
# This should be done automatically by the fbc pipeline using the `run-opm-command` task
COPY --from=builder /app/.konflux/catalog/$PACKAGE_NAME/ /configs/$PACKAGE_NAME
# RUN ["/bin/opm", "validate", "/configs/topology-aware-lifecycle-manager"]
RUN ["/bin/opm", "serve", "/configs", "--cache-dir=/tmp/cache", "--cache-only"]

LABEL operators.operatorframework.io.index.configs.v1=/configs
