apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "true"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    olm.skipRange: '>=4.10.0 <4.18.0'
    operators.openshift.io/infrastructure-features: '["disconnected", "proxy-aware"]'
  name: cluster-group-upgrades-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: PreCachingConfig is the Schema for the precachingconfigs API
      displayName: Pre-caching Config
      kind: PreCachingConfig
      name: precachingconfigs.ran.openshift.io
      resources:
      - kind: Namespace
        name: “”
        version: v1
      version: v1alpha1
    - description: ClusterGroupUpgrade is the Schema for the ClusterGroupUpgrades
        API
      displayName: Cluster Group Upgrade
      kind: ClusterGroupUpgrade
      name: clustergroupupgrades.ran.openshift.io
      resources:
      - kind: Deployment
        name: ""
        version: apps/v1
      - kind: Namespace
        name: ""
        version: v1
      specDescriptors:
      - displayName: Actions
        path: actions
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'This field determines whether the cluster would be running a
          backup prior to the upgrade. Deprecated: Use lcm.openshift.io/ImageBasedGroupUpgrade
          instead for SNO upgrades with built-in backup/rollback functionality'
        displayName: Backup
        path: backup
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:bool
      - description: 'The Batch Timeout Action can be specified to control what happens
          when a batch times out. The default value is `Continue`. The possible values
          are: - Continue - Abort'
        displayName: BatchTimeoutAction
        path: batchTimeoutAction
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Blocking CRs
        path: blockingCRs
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'This field holds a list of expressions or labels that will be
          used to determine what clusters to include in the operation. The expected
          format is as follows: clusterLabelSelectors: - matchExpressions: - key:
          label1 operator: In values: - value1a - value1b - matchLabels: label2: value2
          - matchExpressions: - key: label3 operator: In values: - value3 matchLabels:
          label4: value4'
        displayName: Cluster Label Selectors
        path: clusterLabelSelectors
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'This field holds a label common to multiple clusters that will
          be updated. The expected format is as follows: clusterSelector: - label1Name=label1Value
          - label2Name=label2Value If the value is empty, then the expected format
          is: clusterSelector: - label1Name All the clusters matching the labels specified
          in clusterSelector will be included in the update plan. Deprecated: Use
          ClusterLabelSelectors instead'
        displayName: Cluster Selector
        path: clusterSelector
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Clusters
        path: clusters
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: This field determines when the upgrade starts. While false, the
          upgrade doesn't start. The policies, placement rules and placement bindings
          are created, but clusters are not added to the placement rule. Once set
          to true, the clusters start being upgraded, one batch at a time.
        displayName: Enable
        path: enable
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:bool
      - displayName: Managed Policies
        path: managedPolicies
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Manifest Work Templates
        path: manifestWorkTemplates
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: This field determines whether container image pre-caching will
          be done on all the clusters matching the selector. If required, the pre-caching
          process starts immediately on all clusters irrespectively of the value of
          the "enable" flag
        displayName: PreCaching
        path: preCaching
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:bool
      - description: This field specifies a reference to a pre-caching config custom
          resource that contains the additional pre-caching configurations.
        displayName: PreCachingConfigRef
        path: preCachingConfigRef
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Remediation Strategy
        path: remediationStrategy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      statusDescriptors:
      - displayName: Backup
        path: backup
      - displayName: Clusters
        path: clusters
      - displayName: Computed Maximum Concurrency
        path: computedMaxConcurrency
      - displayName: Conditions
        path: conditions
      - description: Deprecated
        displayName: Copied Policies
        path: copiedPolicies
      - displayName: Managed Policies Compliant Before Upgrade
        path: managedPoliciesCompliantBeforeUpgrade
      - displayName: Managed Policies Content
        path: managedPoliciesContent
      - description: Contains the managed policies (and the namespaces) that have
          NonCompliant clusters that require updating.
        displayName: Managed Policies For Upgrade
        path: managedPoliciesForUpgrade
      - displayName: Managed Policies Namespace
        path: managedPoliciesNs
      - description: 'INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
          Important: Run "make" to regenerate code after modifying this file'
        displayName: Placement Bindings
        path: placementBindings
      - displayName: Placement Rules
        path: placementRules
      - displayName: Precaching
        path: precaching
      - displayName: Remediation Plan
        path: remediationPlan
      - displayName: Safe Resource Names
        path: safeResourceNames
      - displayName: Status
        path: status
      version: v1alpha1
    - description: ImageBasedGroupUpgrade is the schema for upgrading a group of clusters
        using IBU
      displayName: Image-Based Group Upgrade
      kind: ImageBasedGroupUpgrade
      name: imagebasedgroupupgrades.lcm.openshift.io
      resources:
      - kind: Deployment
        name: ""
        version: apps/v1
      - kind: Namespace
        name: ""
        version: v1
      specDescriptors:
      - displayName: Cluster Label Selectors
        path: clusterLabelSelectors
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: IBU Spec
        path: ibuSpec
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Plan
        path: plan
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      statusDescriptors:
      - displayName: Conditions
        path: conditions
      - displayName: Status
        path: observedGeneration
      version: v1alpha1
  description: cluster-group-upgrades-operator is an operator that facilitates platform
    upgrades of group of clusters
  displayName: cluster-group-upgrades-operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAIAAAAP3aGbAAAbp0lEQVR4Xu3dfWhc15nH8StpJGtkOdcSQxSaOhrDkkJpkcIugdJQjcu+saGVloTd/rHF44a+wMJaLoQ2fxTLFJou6RJ5octm2zRjtvtHlwSPU7LsltCMS0IgUCI1YVmXgEdxHaIwtWZkSaOX0cweza0nyrEkz8t9Oc+93w/ByOcG4lia332ec885t6tWq1kAIEG3PgAApiKwAIhBYAEQg8ACIAaBBUAMAguAGAQWADEILABiEFgAxCCwAIhBYAEQg8ACIAaBBUAMAguAGAQWADEILABiEFgAxCCwAIhBYAEQg8ACIAaBBUAMAguAGAQWADEILABiEFgAxCCwAIhBYAEQg8ACIAaBBUAMAguAGAQWADEILABiEFgAxCCwAIhBYAEQg8ACIAaBBUAMAguAGAQWADEILABiEFgAxCCwAIhBYAEQg8ACIAaBBUAMAguAGAQWADEILABiEFgAxCCwAIhBYAEQg8ACIAaBBUAMAguAGAQWADEILABiEFgAxCCwAIhBYAEQg8ACIAaBBUAMAguAGAQWADEILABiEFgAxCCwAIhBYAEQg8ACIAaBBUAMAguAGAQWADEILABiEFgAxCCwAIhBYAEQg8ACIAaBBUAMAguAGF21Wk0fA5pWzecrudx2Pt8Y6Ukmu5PJWCrVGAHcQmChTSqnyjMzlcuX9Qu39IyN9YyP96ZSKrxUhOmXgdYRWGhZrVhcTae3Ll3SL+yve3RUxZYKr96pqa6jR/XLQHMILNNtz82pgFC/VotF61bDpSqXoD726k9yM5WqlUr6haapyutQOq2Si7ILrSKwDLWZyWxms6rt2i8anJqlb2pKffL1a55Rf6q16en9/kitUv8L6g+vwkvlr34N2AuBZZyN2dn12dnqwoJ+YR9dtq0+9vGZGa8LFpVWq6dO6aNuILnQJALLIKrbWk2nt+fn9QvNiU1MqNjy6PGcd2m1m5Nc/dPTXocvhCKwTOFWt+VFbKkY3bxwQR/1kjPP1ZdOBzVVBzMRWEZwvX5RH3hVp6gPvH6hRbViUcWoz2m1W+/kZN/UVOf/IwgHAit4rqdVg+qwVLXV9qe9ms+vTE213aK6yJmnUxHMJFfEEVgBq+RyN0+c0EddpWJLZZbqsFqaGNqYnS3PzHTeorqLVjHiCKwgqRJmeXzct1Bw2quD152rHnArm1VR1fxjykD0nTypksvdqTqYj8AK0s1U6oCtLd5x1nDt7Pi7tQBV5VRlbm57bq6l9euBU/8jzlQdBVdEEFiBUT3X2pkz+ijaQsEVEQRWMFRFU0omfWsGI8J5Nsp2xRDjPKxgGDifHQLb8/Orp06pO8Ha9HR114k3CA0qrACoz1Lp+HF9FG6jTwwfKqwAqPJKH4IHNi9cuHnixPL4+GYmo1+DTFRYfqO8CgTPE8OBCstvG9ztg1BdWFg7c6aUTO7MHtZPFoNEVFh+Kx49ynR7sLps+9D0dKtL/2ECKixfbWYypFXg1Ldg/dw51ZivptM8TJSFwPIV/aBRNi9cULFFkygILaF/mG43ltMk9k9PMyVvOCos/2xls/oQzPCHJrE+Ja9fg0mosPyzPD5uwtlSOFiHh4jBUwSWT7bn5pYfeEAfhaliExMDs7OcF2gaWkKfMN0uS+XyZXWD2Tlln/l4k1Bh+aSUTBp+JB72pDrEw5kMGxINQYXlh533NpNWMqlv3M0TJyi1DEFg+WF9dlYfgigb58/fTKXUjUe/AH/REvqB7Tjh0GXbqj3snZrSL8AvVFie28pmSatwUN/Hlb/+aw6rCRCB5blN1ouGy+qpU2RWUGgJvcXZ7WF1+LnnWFzqPyosb9EPhpWqs9hr5T8Cy1v0gyHG6TT+oyX0kOoHi0ND+ihCJDYxcSSX00fhGSosD9EyhF7l8mUm4P1EheUhjmeIgu7RUZvG0C9UWF6p5vOkVRRUFxYosnxDYHmFfjA62HrlGwLLK5wnEx2qlGaboT8ILE+oH1/6wUjh/uQPAssT/PhGDTMA/uApoSc4ri+C7KtXeTOr16iw3MdxfdFEkeUDAst9PDOKpi2WvHuPltB9HNcXTV22fZRjlD1GheUyjmeILPV9Z3GD1wgsl3E8Q5QRWF4jsFzGzGuUMY3lNQLLTZuZDP1glFUILI8RWG6iH4y46sICry/0FIHlGvWTunXpkj6KiKHI8hSB5Rpmr2AxjeUxAss19IOweFDoMRaOuoPj29EwxGfKM1RY7uDMSTQwjeUdAssdnCeDBqaxvENguYDj27Eb01jeIbBcwPNB7EZL6B0CywX0g9iNXdDeIbA6RT+I2xFYHiGwOkV5hdsx7+4R1mF1iuPbcTteB+0RKqyOcHw79sQuaI8QWB2hH8R+eFboBQKrI7/neAbso8K8uwcIrPblcrlB5imwDyosLxBY7cvQD2J/lcuX9SF0jKeEbSoWi8mhoav6MPChI6+8Ekul9FF0gAqrTaq84vB2HIzlo64jsNo0W3+98wpnYGF/LB91HYHVjlwut1BffvVGX59+DbiFeXfXEVjtcMor5dzi4kevAB+qlUpVniO7isBqWT6fv3Rr+dVblvXOyMhHrwMfoshyF4HVMm01wzcpsrA/prHcRWC1TAusVy3rlxRZ2AcPCt1FYLUmm8060+27Pba4uNnfrw0Cyvb8PLugXURgtWbP1e0ly3p0fV0fBeqYxnIRgdWC3dPtGtUYvpBI6KMAu6BdRWC1YM/yquGrhcIVMgu3ocJyEXsJP+T8YNWKxcYtcXturjEBob5+qrv7e0tLt/71PdiW9XoicU+hoF9AtPEuaLdELrBUAO0cE5rPb+fz1cY/t82j7+l4fbrqYJ+2rJfj8d5yWb+ACGMXtFtCHlhOPG3lck4wdXLix2vHjn3h2jV9dC9kFjQDTz99aHpaH0XrQhhYKqFUc6dCyt0D179sWS/pY/sis7Bb7+TkIG/bdUNIAktVT1vZrAopFVW10h37tnY00w/u9rBl/bs+hojqsu2jrMZyg+zAUjXURiajosrFSmpPhZGR+1vfgqMy6yfUWaizr17tTib1UbRI5LIGVU+tTU+XksnlBx7YOH/e67RSXo/F9KEmqBbyT8vlrXhcv4DoYXGDK4QF1mYmczOVKh0/7k9ONVxZW9OHmvMWmYU6dkG7QkxgqahSJdXqqVOdPOlr268OXH51MCezlm1bv4AoYRe0KwQEViOq/Cyp3KUya6xUem94WL+AyGAXtCuMDizV9i+Pj5sQVa/qAy0rWdZnb9x4g707EcY0VucMDSx1L1qbnr554oS6L+nXxFKZ9ZeFAnukI4td0J0zMbCcwmrj/Hn9Qih8tVB4PB6vDAzoFxB2VFidM24d1sbs7NqZM/po0FpdNXpHn7asn9v2Xd6scYWx2AXdIbMqrNV02sC0sur54i5nGp4praihyOqQKYFVKxZVWm1euKBfMIMXSxKcKa1nWO4QJSxu6JApgWVyWikPj47qQy55olSasCxWaUUEy0c7ZERgqbTa2ufoYUN8plLRh9xDexgdVFgdCj6wyjMzJtdWjtHr1z0tgZz2kKeHoVddWCj+5jf6KJoWcGBVcrn1c+f0USM9pA+479ly+U/W1jgYPtz+78c/1ofQtCADy5lo10dN9a1jx/QhD7yr2s9C4bv9/ZRaYVV79119CE0LMrBUMxj4npvmferaNU+7wt2eXl+n1AqropyfeQMFFljVfF7cWvZv+/gszym1Ho/Head0yHx8aanILuh2BRZYqrzSh4z3lc1N/xKr7tly+RPr678cGdEvQLIcixvaFUxgqfLK/CeDt+stl/0sshwly3p0cfGLlvU+HWJYEFhtCyaw1mdn9SEh/C+yHK9a1ifrk/EcXhoCBFbbggmsLbGvPFJF1g+Cq3SeXl+/v1ymQxStWK3Oh+jQJJ8FEFjuvi7Qf48UCq7vhW6e0yFOWNY7xJZMb3fvfOgostoTQGBtZDL6kDQ/C67IcrxlWQ/WJ7bYhCjO75aXLQKrXQEEVghO2LinUHjSgKR41bKSpdLj8TixJYjzQhMCqz0BHOC31NWlD8k0Ua90DPFYPP6dvj5OBDRf4zBI/z96IeB3hRWC8qpBNYbmFDbPlstjpdIzts1jRJO9n0g0bikUWW3wO7Cq+bw+JJZqDJ8x6c1dpfrpWveXyyq2VoaG9MswwE+3txtfz3HUTOv8DqztEAWW8uc3bpwxbOuME1v3LS0xt2Wgn+56Iy8VVhv8Dqzw+c76+qNGnqygmkRnSp4l8oZ4Z2Rk90EN6y+/vLP/P1y3cK/5HVhhmsNq+GGtFuDKrIOp2PpkofBF1m0Z4JuLi7t/+97q6vq5c6Xjx1fTaWKrSX4HVij1lssvx+PGZpZVXwDx4OLiuGX9cmSEWflAvJFIaO8Pbzxi3rxwgdhqEoHlDpVZRj003NO79VXy95fLPxgaYnrLT5WBga8VCvqoZS3ce2/ja2KrGQSWa+4pFF4bHjY/BkqW9b2lpWSppPrE13w5RhVP1Gq7Z68aXo/FtBFi62AElps+duOGiMxyqA7lC9euHbcsCi5P/WJ4+NlyWR+te2mfTbVObK1NT9c46u+j/A6s7mRSHwoXWZll7Sq4Jpjh8oBKqy/duKGP3nLwTomN8+dLyeSG2LOYvEBguU9cZjneqs9wjZTLX7ast2kV3XBwWln1WcWD7xC1UmntzJnl8fFQPl5vg++BdfSoPhRGKrOu9Peb/NzwAC9Z1ufqreLj8TjJ1bY7ppXjvSY2S2zPz988cWI1naZD9DuwesbH9aGQ6ltfN3ytw8FK9TVcJFcbKgMD6m+smbSy9pp338/OxFYyKffwS1f4fVqDukUUo7TNTf3sPlGr7TfnKs7DlvWNY8fGVlYGd20xwW7vJxJ/WygcPDm122Px+FMt/nj0Tk4ezmS6otGsaPwOLEXdJUSfONqG7/b3P72+ro9KpirHr4yMpGKx0evX9WtRtRWPf79Wa/Ubrf4mL+tjd9Zl24PZbCyV0i+EXQCBpVpxia/M6dAvhoe/fuNG+E6rsi3rIcv6m3vv/Uylkvjo1pPoUFH1k76+75faPI2sqdZxL4dOnx6I2DPEAAJrM5NZPXVKH42A94aH/+rGjT0XEIbDffV6IVLhtTI09B/VattR5fjtyEjbf109Y2Oq1IrCw3dHAIFVzedLx4/ro9GgbsWPlMvanrJQsuvh9Ui9bfzYjRu9LU7TmO/tY8f+8dq1l/ThdvxmdPTjHUySqPbwcCbTOzWlXwijAAJLWR4f347wm46ese0nOroly+MUXw+PjqriS25+qfvNlUTiQqHwfLns4vfv58eOffbaNX20Rf1nz8YFvk29VcEE1sbs7NqZM/polFypP0sKcXt4MKf++tzQ0CcGBh6IxUY++MDYCFMhpXr5XKXywuKiR6Xxv4yOfqmDCquh7+TJgdnZcD89DCawotwVNqhPwt93dT2/tqZfiKqH6kGmqrDDlYpKsf719bZndjqxMjT0+4GB12OxX3/wwRvlcvMLFNrmVmBZ9SmtI7lciDMrmMBSVqamti5d0kejJ6xPD1306XqQOVnmjKi+sufWess2qjN1q1i8+271xXal4qzbVNl0pd7l+RBPt3OlJWzoHh0dzGbDukI7sMCq5HI3T5zQRyNp2bb/rlTyqN2A+TqcdL9dl22rOiuUmeX31pyGWCrVfeuGGXF3lUovWtaPjD//D1LUSqWbqdR2GN/KE1hgKVF4qNG8RwqFedt+SB9G+LlbXjnCmlmBtYSOCG7TuaM36g8QmdWKiPssy7tQCV9vGGSFZVFk7eXBQuG38bhprzuER/7swPOwOhS+OivgCsuiyNrf+4nE1woFJuPDzd1HhHsKU50VcIWlHM5k9CHU3VMovGhZz4+MMBkfYg/u9TYdd6k6a2VqKhyH/wUfWLFUqndyUh/FLZ9fXFQd4pM2b4kIoYfrL4jTRz2gmhjVG4Ygs4IPLGVnPwGfx/2pn+mvl0rztv2Yl/Md8N+3fDzHdXt+fm16Wh+VxojA6k4mmX2/o7tKpafK5TxLH8LiPsv6lMezV5rNCxekv4Mn+En3hogf4dCSd0ZGvunZXlz44/mRkc8HsVnyyCuvyD2q1KDAqubzKrNqETt3pRPEllyqTH5RH/NJl23b+bzQDdJGtIQOGsNW/dHiovqhf2NkhCZRnH9LJPQhv6iaYDWd1keFMKjCcnCKQ3tUtfXM8nJoXs8Tbk/a9teD7iQGL16UeEipcYFVKxZVY8hS0vYs2/Z3NzeJLZMF2AzuJrQxNKgldKi/wcFovyqyE86TxEXWbZnqPst6wYy1KUIbQ+MCy6q/Hfrwc8/po2ias27rav05lNxXT4ePuoX81/CwPytFm7F16VIll9NHzWZcS9gQzdcXeuH9ROKfVlfpE4Ol0uq14eGPNff+et90j46qxlAfNZi5gaXcTKUql9t4LS72sBWPv3j48D+38hZ1uMXMtHKobqZPTm9odGDVisWdwzFYTeoqp+By90VVOIDqyn+WSNzj/Sbn9sgqsowOLKueWaVkktWkXnjt2LF/delVoNjPowMDP6zVzJm32pOgIsv0wFK25+Z2NpqTWd6gVfTOjxKJR0wtrHYTVGQJCCyLzPLFytDQ//T0kFyuMLwNvJ2UIktGYFlklo9Ucr0yMPCf16/TLbbBtqwfCCmsdotNTByRsMRBTGBZvMrQd6pbfCORyBYKzNA36Unb/srmpuEzVvu56803zT9G2cSFo/uJpVIsKPWT+uB99tq1p8rlq5b1v4nE0yxD3d9j8Xi+vkNQaFopGxIOK5dUYTlUnbVzQDW9YUBU2XUlkfjvlZWfLy0x26UawG9Lrqp2EzH1Li+wLOazjBHl8HrYsr7h/QtvfGZ+VygysCwyyzwqvN4bHn49FntpYeFVywrrN0Y1xf+QSPzF9vbg0pJ+Tb5Dp08PmH2GstTAssgss60MDeUHB3+9ufnC4uK7lvWufl0Su34mjKqnxlZWQplTDT1jY3eZ/dZVwYFl1U9VXpmaYu+O+VT9tXj33W9WKlfW1n5V7x8Nv8/Y9WLqkZGRVCw2ev26fjm8ji4tmXxIluzAsthvKNnvRkeL1erb3d2/W15WKaYiLMCJsPvq/6iE+uO+vmTYK6kDGP6KCvGBZdUza216mrNoQkMFmfp1oVq91r2z7OalhQWnHHMl0Zzz71UB9XD9v/KZSuVwpZII4u01Zuo/e9bkVyuEIbAcKrM2zp/XRxFeTpupj+7l45y43bTeyUmTj/wNT2Apm5nM6qlT+iiAphm+RydUgWXx6BDo2JDBmSBpa04zesbH7Xy+Z2xMvwBAvrAFltJ19Ohdc3N9J0/qFwA0oVYs6kPGCGFgOQ5nMoefe66Ll10BLdo2eO1oaANL6Uunj+Ry3fWn1wBCIMyBZdWntFR72Ds5qV8AIFDIA8uqT2kNZrO0h0AIhG1ZwwFUZ76aTrOJBziYydsJw19hNTjt4aHTp/ULAHYxNq2sSFVYDZVcTpVaVbZrAHth4ahZYqkUM/HAngx/qh7FwLJuzcQPXrzITDywW3cyqQ+ZJKKB5eidmrLzeUotoIHAMhqlFrAbgSWAU2rxABGI8dYcQXiAiIizr141uciiwvqIWCqlSq3+s2f1C0AEdNm2yWllEVh7is/MqPtMbGJCvwCEmsmvn3AQWHtT95kjudzgxYuGL0sBXNRrfGAxh3UHtWJxfXZ2/dw5/QIQOoZPYFkEVpOq+fza9PTWpUv6BSAsVDNh5/P6qGFoCZuibjuD2eyRV17htHiEVe/UlD5kHiqslm1mMqra4sU8CJm73nyzx+xFWBaB1R5nYmtjdpbYQjiI6ActWsL2dB09Gp+Z4d08CI3+6Wl9yEhUWJ1iPh7Sddm2Kq9MPrevgQqrU435eBaaQqjeqSkRaWVRYbmrksuVZ2Yqly/rFwCDmb/8qoEKy02xVOpILke1BUH6Tp6UklYWFZZ3qLYggqDyyqLC8g7VFszXf/asoLSyqLD8QbUFAwl6ONhAheWHRrXFui2Y43AmIyutLCos/1XzeVVtbV64oF8AfNQ7OTmYzeqjxiOwgqFiayOTYXMPAiGxGXQQWEGqFYtb2awquDhFHn7aeRZk/Fl9e2IOK0jqFteXTqt73eDFizxMhD/6z54VmlYWFZZRtufm1mdnmd6Cd4ROXTUQWMZRfeJmJqOSiz4R7uoZGzuSy0mcumogsMy1lc1uZDKcAwFXyJ1o343AMp3zPFHVXBRcaJtKK1VbmX+g6B0RWGJQcKE9oUkri8ASh4ILLQlTWlkEllyVXG6n4MpmWXqK/YRgll1DYMnmLD3dzGZpFaGJTUwMZrNhSiuLwAoN1So6k1zb8/P6NUTPodOnB2Zn9VH5CKywUcm1PjurwotJrmjqsm0VVX3ptH4hFAis0Nqem3MmuUiu6OgZG1NtoKwz+VpCYIUfyRUR/WfPxmdm9NFwIbAiRCXXzvR8Nss8V8jEJiZUGxiatQsHILCiyJmhV+HFqc3Sddm2qqoOCXlvc+cIrEhzVkVs5XKs55Lo0OnTKq1CtnDhYAQW/qCSy+3UXLkcDaP5+k6eVFEV4sn1/RBY0KmGUcUWZZeZIhtVDgILB9mem/tDeLGSPlBdtt2XTvdPT0c2qhwEFprlJJf6lal6P3WPjqqcUmkVqbmq/RBYaMfOVNfcnJNftI1eUCVV79TUoXRa7vnrXiCw0CmVXE547XzBhH3Heicn+6amwrq3pkMEFtxUKxY/DK+5OdbWN8mpp3pTKfUrrd8BCCx4iPw6WM/YmOr4VD1F39ckAgu+cia/tvN5J8IiOP8Vm5joGR9XxZQKKYqpVhFYCJJTgu0UX8Xizvy9+m3oZsFUGaUSKjY+vvMrlVRnCCwYp5rPV+slWLUeZ06oSanFVAGl6iYnobqTyShsSPYTgQUxnCBT+VWZm2v81qo/pvQ5zlTRpFLJCSb1W5VNzte0eF4jsBAeTi3W+O1WLvfhtVu0f6dBVUN7LiLv3dXEEUmBI7AAiNGtDwCAqQgsAGIQWADEILAAiEFgARCDwAIgBoEFQAwCC4AYBBYAMQgsAGIQWADEILAAiEFgARCDwAIgBoEFQAwCC4AYBBYAMQgsAGIQWADEILAAiEFgARCDwAIgBoEFQAwCC4AYBBYAMQgsAGIQWADEILAAiEFgARCDwAIgBoEFQAwCC4AYBBYAMQgsAGIQWADEILAAiEFgARCDwAIgBoEFQAwCC4AYBBYAMQgsAGIQWADEILAAiEFgARCDwAIgBoEFQAwCC4AYBBYAMQgsAGIQWADEILAAiEFgARCDwAIgBoEFQAwCC4AYBBYAMQgsAGIQWADEILAAiEFgARCDwAIgBoEFQAwCC4AYBBYAMQgsAGIQWADEILAAiEFgARCDwAIgBoEFQAwCC4AYBBYAMQgsAGIQWADEILAAiEFgARCDwAIgBoEFQAwCC4AYBBYAMQgsAGIQWADEILAAiPH/MiKT6dBv5iYAAAAASUVORK5CYII=
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - acm lifecyclemanagement upgrades cluster
  links:
  - name: Cluster Group Upgrades Operator
    url: https://cluster-group-upgrades-operator.domain
  maturity: alpha
  provider:
    name: Red Hat
  replaces: cluster-group-upgrades-operator.v4.14.0
  version: 0.0.0
