apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: cluster-group-upgrades-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ClusterGroupUpgrade is the Schema for the ClusterGroupUpgrades
        API
      displayName: Cluster Group Upgrade
      kind: ClusterGroupUpgrade
      name: clustergroupupgrades.ran.openshift.io
      version: v1alpha1
  description: cluster-group-upgrades-operator is an operator that facilitates platform
    upgrades of group of clusters
  displayName: cluster-group-upgrades-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - acm lifecyclemanagement upgrades cluster
  links:
  - name: Cluster Group Upgrades Operator
    url: https://cluster-group-upgrades-operator.domain
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
