// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGroupUpgrade) DeepCopyInto(out *ClusterGroupUpgrade) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGroupUpgrade.
func (in *ClusterGroupUpgrade) DeepCopy() *ClusterGroupUpgrade {
	if in == nil {
		return nil
	}
	out := new(ClusterGroupUpgrade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterGroupUpgrade) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGroupUpgradeList) DeepCopyInto(out *ClusterGroupUpgradeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterGroupUpgrade, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGroupUpgradeList.
func (in *ClusterGroupUpgradeList) DeepCopy() *ClusterGroupUpgradeList {
	if in == nil {
		return nil
	}
	out := new(ClusterGroupUpgradeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterGroupUpgradeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGroupUpgradeSpec) DeepCopyInto(out *ClusterGroupUpgradeSpec) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemediationStrategy != nil {
		in, out := &in.RemediationStrategy, &out.RemediationStrategy
		*out = new(RemediationStrategySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PlatformUpgrade != nil {
		in, out := &in.PlatformUpgrade, &out.PlatformUpgrade
		*out = new(PlatformUpgradeSpec)
		**out = **in
	}
	if in.OperatorUpgrades != nil {
		in, out := &in.OperatorUpgrades, &out.OperatorUpgrades
		*out = make([]OperatorUpgradeSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGroupUpgradeSpec.
func (in *ClusterGroupUpgradeSpec) DeepCopy() *ClusterGroupUpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterGroupUpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGroupUpgradeStatus) DeepCopyInto(out *ClusterGroupUpgradeStatus) {
	*out = *in
	if in.PlacementBindings != nil {
		in, out := &in.PlacementBindings, &out.PlacementBindings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PlacementRules != nil {
		in, out := &in.PlacementRules, &out.PlacementRules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]PolicyStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGroupUpgradeStatus.
func (in *ClusterGroupUpgradeStatus) DeepCopy() *ClusterGroupUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterGroupUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesiredUpdateSpec) DeepCopyInto(out *DesiredUpdateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesiredUpdateSpec.
func (in *DesiredUpdateSpec) DeepCopy() *DesiredUpdateSpec {
	if in == nil {
		return nil
	}
	out := new(DesiredUpdateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorUpgradeSpec) DeepCopyInto(out *OperatorUpgradeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorUpgradeSpec.
func (in *OperatorUpgradeSpec) DeepCopy() *OperatorUpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(OperatorUpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformUpgradeSpec) DeepCopyInto(out *PlatformUpgradeSpec) {
	*out = *in
	out.DesiredUpdate = in.DesiredUpdate
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformUpgradeSpec.
func (in *PlatformUpgradeSpec) DeepCopy() *PlatformUpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformUpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatus) DeepCopyInto(out *PolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatus.
func (in *PolicyStatus) DeepCopy() *PolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationStrategySpec) DeepCopyInto(out *RemediationStrategySpec) {
	*out = *in
	if in.Canaries != nil {
		in, out := &in.Canaries, &out.Canaries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationStrategySpec.
func (in *RemediationStrategySpec) DeepCopy() *RemediationStrategySpec {
	if in == nil {
		return nil
	}
	out := new(RemediationStrategySpec)
	in.DeepCopyInto(out)
	return out
}
