apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-a
  namespace: default
spec:
  managedPolicies:
    - policy1-common-cluster-version-policy
    - policy2-common-pao-sub-policy
    - policy3-common-ptp-sub-policy
  blockingCRs:
  - name: cgu-c
    namespace: default
  enable: false
  clusters:
  - spoke1
  - spoke2
  - spoke3
  remediationStrategy:
    canaries:
    - spoke1
    maxConcurrency: 2
---
apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-b
  namespace: default
spec:
  managedPolicies:
    - policy1-common-cluster-version-policy
    - policy2-common-pao-sub-policy
    - policy3-common-ptp-sub-policy
    - policy4-common-sriov-sub-policy
  blockingCRs:
    - name: cgu-a
      namespace: default
  enable: false
  clusters:
  - spoke4
  - spoke5
  remediationStrategy:
    maxConcurrency: 1
---
apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-c
  namespace: default
spec:
  managedPolicies:
    - policy1-common-cluster-version-policy
    - policy2-common-pao-sub-policy
    - policy3-common-ptp-sub-policy
    - policy4-common-sriov-sub-policy
  enable: false
  clusters:
  - spoke6
  remediationStrategy:
    maxConcurrency: 1

