apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: test
  namespace: default
spec:
  clusters:
  - spoke1
  enable: true
  preCaching: true
  remediationStrategy:
    canaries: []
    maxConcurrency: 1
    timeout: 240
