apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: test
  namespace: default
spec:
  clusters:
  - spoke1
  - spoke2
  - spoke3
  - spoke4
  - spoke5
  - spoke6
  remediationAction: inform
  remediationStrategy:
    canaries:
    - spoke1
    maxConcurrency: 2
  operatorUpgrades:
    - name: ptp-operator
      namespace: openshift-ptp
      channel: "4.9"
