---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: upgrade
  namespace: default
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: upgrade
      spec:
        namespaceselector:
          exclude:
          - kube-*
          include:
          - '*'
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: config.openshift.io/v1
            kind: ClusterVersion
            metadata:
              name: version
            spec:
              channel: stable-4.9
              desiredUpdate:
                version: 4.9.4
              upstream: https://api.openshift.com/api/upgrades_info/v1/graph
            status:
              history:
                - state: Completed
                  version: 4.9.4
        remediationAction: inform
        severity: low
  remediationAction: inform

---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: upgrade
  namespace: default
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: upgrade
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: upgrade

---
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: upgrade
  namespace: default
spec:
  clusters:
  - name: sno
