apiVersion: ran.openshift.io/v1alpha1
kind: PreCachingConfig
metadata:
  name: example-config
  namespace: example-ns
spec:
#  Examples
#  additionalImages:
#    - quay.io/foobar/application1@sha256:3d5800990dee7cd4727d3fe238a97e2d2976d3808fc925ada29c559a47e2e
#    - quay.io/foobar/application2@sha256:3d5800123dee7cd4727d3fe238a97e2d2976d3808fc925ada29c559a47adf
#    - quay.io/foobar/applicationN@sha256:4fe1334adfafadsf987123adfffdaf1243340adfafdedga0991234afdadfs
#  spaceRequired: 45 GiB
#  overrides:
#    preCacheImage: quay.io/test_images/pre-cache:latest
#    platformImage: quay.io/openshift-release-dev/ocp-release@sha256:3d5800990dee7cd4727d3fe238a97e2d2976d3808fc925ada29c559a47e2e
#    operatorsIndexes:
#      - registry.example.com:5000/custom-redhat-operators:1.0.0
#    operatorsPackagesAndChannels:
#      - local-storage-operator: stable
#      - ptp-operator: stable
#      - sriov-network-operator: stable
#  excludePrecachePatterns:
#    - aws
#    - vsphere
