apiVersion: ran.openshift.io/v1alpha1
kind: PreCachingConfig
metadata:
  name: pre-caching-config
  namespace: default
  annotations:
    cluster-group-upgrades-operator/name-suffix: kuttl      
spec:
  overrides: {}
  additionalImages:
    - image1:latest
    - image2:latest
  spaceRequired: 40GiB
