apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu
  namespace: default
  annotations:
    cluster-group-upgrades-operator/name-suffix: kuttl      
spec:
  managedPolicies:
    - policy0-common-config-policy
  enable: false
  preCaching: true
  clusters:
  - spoke6
  - spoke2
  - spoke1
  - spoke5
  remediationStrategy:
    maxConcurrency: 4

 