apiVersion: operator.openshift.io/v1alpha1
kind: ImageDigestMirrorSet
metadata:
  name: topology-aware-lifecycle-manager-digest-mirror-set
spec:
  imageDigestMirrors:
  - mirrors:
    - quay.io/redhat-user-workloads/telco-5g-tenant/topology-aware-lifecycle-manager-4-14
    source: registry.redhat.io/openshift4/topology-aware-lifecycle-manager-rhel8-operator
  - mirrors:
    - quay.io/redhat-user-workloads/telco-5g-tenant/topology-aware-lifecycle-manager-bundle-4-14
    source: registry.redhat.io/openshift4/topology-aware-lifecycle-manager-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/telco-5g-tenant/topology-aware-lifecycle-manager-precache-4-14
    source: registry.redhat.io/openshift4/topology-aware-lifecycle-manager-precache-rhel8
  - mirrors:
    - quay.io/redhat-user-workloads/telco-5g-tenant/topology-aware-lifecycle-manager-recovery-4-14
    source: registry.redhat.io/openshift4/topology-aware-lifecycle-manager-recovery-rhel8
