---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/nudge_renovate_config_map: namespace-wide-nudging-renovate-config
    build.appstudio.openshift.io/repo: https://github.com/openshift-kni/cluster-group-upgrades-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" && files.all != ["konflux_clusterserviceversion_overlay.data"]
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: topology-aware-lifecycle-manager-4-19
    appstudio.openshift.io/component: topology-aware-lifecycle-manager-recovery-4-19
    pipelines.appstudio.openshift.io/type: build
  name: topology-aware-lifecycle-manager-recovery-4-19-on-push
  namespace: telco-5g-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/telco-5g-tenant/topology-aware-lifecycle-manager-recovery-4-19:{{revision}}
    - name: build-platforms
      value:
        - linux/x86_64
    - name: dockerfile
      value: Dockerfile.recovery
    - name: build-args-file
      value: konflux_build_args.conf
    - name: hermetic
      value: "true"
    - name: prefetch-input
      value: gomod
    - name: build-source-image
      value: "true"
  pipelineRef:
    name: build-pipeline
  taskRunTemplate: {}
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
