---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-kni/cluster-group-upgrades-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: topology-aware-lifecycle-manager-4-19
    appstudio.openshift.io/component: topology-aware-lifecycle-manager-aztp-4-19
    pipelines.appstudio.openshift.io/type: build
  name: topology-aware-lifecycle-manager-aztp-4-19-on-pull-request
  namespace: telco-5g-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/telco-5g-tenant/topology-aware-lifecycle-manager-aztp-4-19:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: dockerfile
      value: Dockerfile.aztp
    - name: build-args-file
      value: build_args_konflux.conf
    - name: hermetic
      value: "true"
    - name: prefetch-input
      value: "gomod"
    - name: build-source-image
      value: "true"
  pipelineRef:
    name: build-pipeline
  taskRunTemplate: {}
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
