---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-kni/cluster-group-upgrades-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" &&
      target_branch == "release-4.19" &&
      (
        '.konflux/container_build_args.conf'.pathChanged() ||
        '.tekton/build-pipeline.yaml'.pathChanged() ||
        '.tekton/topology-aware-lifecycle-manager-precache-4-19-pull-request.yaml'.pathChanged() ||
        'config/***'.pathChanged() ||
        'Dockerfile.precache'.pathChanged() ||
        'go.mod'.pathChanged() ||
        'go.sum'.pathChanged() ||
        'hack/***'.pathChanged() ||
        'pkg/***'.pathChanged() ||
        'pre-cache/***'.pathChanged() ||
        'telco5g-konflux'.pathChanged() ||
        'telco5g-konflux/***'.pathChanged() ||
        'vendor/***'.pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: topology-aware-lifecycle-manager-4-19
    appstudio.openshift.io/component: topology-aware-lifecycle-manager-precache-4-19
    pipelines.appstudio.openshift.io/type: build
  name: topology-aware-lifecycle-manager-precache-4-19-on-pull-request
  namespace: telco-5g-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/telco-5g-tenant/topology-aware-lifecycle-manager-precache-4-19:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: build-platforms
      value:
        - linux/x86_64
    - name: dockerfile
      value: Dockerfile.precache
    - name: build-args-file
      value: .konflux/container_build_args.conf
    - name: hermetic
      value: "true"
    - name: prefetch-input
      value: ""
    - name: build-source-image
      value: "true"
    - name: skip-sast-coverity
      value: "true"
    - name: additional-tags
      value: []
    - name: additional-labels
      value:
        - name=openshift4/topology-aware-lifecycle-manager-precache-rhel9
  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-topology-aware-lifecycle-manager-precache-4-19
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
