apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-kni/cluster-group-upgrades-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "release-4.15"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: topology-aware-lifecycle-manager-fbc-4-15
    appstudio.openshift.io/component: topology-aware-lifecycle-manager-fbc-4-15
    pipelines.appstudio.openshift.io/type: build
  name: topology-aware-lifecycle-manager-fbc-4-15-on-pull-request
  namespace: telco-5g-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/telco-5g-tenant/topology-aware-lifecycle-manager-fbc-4-15:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: .konflux/Dockerfile.catalog
  pipelineRef:
    name: fbc-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-topology-aware-lifecycle-manager-fbc-4-15
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
