apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-invalid-hub-template
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-invalid-hub-template-config
      spec:
        namespaceselector:
          exclude:
          - kube-*
          include:
          - '*'
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: invalid-hub-template-cm
              namespace: default
            data:
              key: '{{hub fromConfigMap "default" "site-data" "value" hub}}'
        remediationAction: inform
        severity: low
  remediationAction: inform
