apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: test
  namespace: default
spec:
  clusters:
  - my-cluster
  enable: true
  preCaching: true
  managedPolicies:
  - common-cluster-version-policy
  - common-operator-policy
  - common-catalog-source-policy
  remediationStrategy:
    canaries: []
    maxConcurrency: 1
    timeout: 240
