apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-upgrade-complete
  namespace: default
spec:
  managedPolicies:
    - policy1-common-cluster-version-policy
    - policy2-common-pao-sub-policy
  enable: false
  clusters:
  - spoke1
  remediationStrategy:
    maxConcurrency: 1
