# We use this IDMS to check if the images in the FBC are resolvable using the staging or production catalog.
apiVersion: operator.openshift.io/v1alpha1
kind: ImageDigestMirrorSet
metadata:
  name: fbc-images-resolvable-integration-test-idms
spec:
  - mirrors:
    - registry.stage.redhat.io/openshift4/topology-aware-lifecycle-manager-rhel9-operator
    source: registry.redhat.io/openshift4/topology-aware-lifecycle-manager-rhel9-operator
  - mirrors:
    - registry.stage.redhat.io/openshift4/topology-aware-lifecycle-manager-operator-bundle
    source: registry.redhat.io/openshift4/topology-aware-lifecycle-manager-operator-bundle
  - mirrors:
    - registry.stage.redhat.io/openshift4/topology-aware-lifecycle-manager-aztp-rhel9
    source: registry.redhat.io/openshift4/topology-aware-lifecycle-manager-aztp-rhel9
  - mirrors:
    - registry.stage.redhat.io/openshift4/topology-aware-lifecycle-manager-precache-rhel9
    source: registry.redhat.io/openshift4/topology-aware-lifecycle-manager-precache-rhel9
  - mirrors:
    - registry.stage.redhat.io/openshift4/topology-aware-lifecycle-manager-recovery-rhel9
    source: registry.redhat.io/openshift4/topology-aware-lifecycle-manager-recovery-rhel9
